#
sudo: required
language: generic 
services: 
    - docker

before_install:
    - docker build -t hugo/docker-react -f Dockerfile.dev .
script: 
    - docker run -e CI=true hugo/docker-react npm run test -- --coverage

